# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  sum:
    desc: run repomix
    cmds:
      - repomix --include "**/*.json,**/*.js,**/*.css,**/*.html" --output "./docs/toast.xml"
    silent: true
